apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-cfgmap"
data:
  {{- range $key, $val := .Values.configuration }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
  {{- range $key, $val := .Values.vaultValues }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
