"""DE expert implementation."""

from __future__ import annotations

from pathlib import Path

from examples.polecat_swarm.agents.base_expert import BaseExpert
from examples.polecat_swarm.subagents.api_doc_writer import APIDocWriter
from examples.polecat_swarm.subagents.user_doc_writer import UserDocWriter
from examples.polecat_swarm.types import ExpertResult


class DocumentationExpert(BaseExpert):
    role = "DE"

    def run(self) -> ExpertResult:
        api_writer = APIDocWriter(
            docs_path=self.docs_path,
            worktree=self.worktree,
            log=self._child_log("APIDocWriter"),
        )
        user_writer = UserDocWriter(
            docs_path=self.docs_path,
            worktree=self.worktree,
            log=self._child_log("UserDocWriter"),
        )

        qa_notes = self._load_latest_qa_notes()
        api_path = api_writer.run(self.bead, qa_notes=qa_notes)
        notes_path = user_writer.run(self.bead, summary="Documentation updates generated by DE.")

        runbook_path = Path(self.worktree) / self.docs_path / "runbook.md"
        runbook_path.parent.mkdir(parents=True, exist_ok=True)
        runbook_path.write_text(
            "# Runbook Updates\n\n- Validate deployment in staging.\n- Monitor error rates post-release.\n",
            encoding="utf-8",
        )

        artifact_summary = self.write_artifact(
            "documentation_summary.md",
            "\n".join(["# Documentation Summary", f"- API docs: {api_path}", f"- Release notes: {notes_path}", f"- Runbook: {runbook_path}"]),
        )

        return ExpertResult(
            status="success",
            notes="Documentation artifacts generated",
            artifacts=[api_path, notes_path, str(runbook_path), artifact_summary],
        )

    def _load_latest_qa_notes(self) -> str:
        """Load QES's qa_report.md, preferring convoy siblings over mtime scan.

        Strategy:
          1. Check bead labels for convoy-sibling bead IDs that match
             a ``qa_report.md`` in the specs directory.
          2. Fall back to the latest ``qa_report.md`` by modification time
             (backward-compatible with pre-convoy runs).
        """
        spec_root = Path(self.worktree) / ".gastown" / "specs"
        if not spec_root.exists():
            return ""

        # 1. Prefer convoy siblings — check sibling bead dirs for qa_report.
        #    The bead's labels include the convoy ID, and all sibling beads
        #    share that convoy label.  Look for qa_report.md in sibling dirs.
        bead_labels = set(str(lbl) for lbl in (self.bead.get("labels") or []))
        for label in bead_labels:
            if label.startswith("convoy-"):
                # Scan spec dirs for any sibling in this convoy that has qa_report.
                for spec_dir in spec_root.iterdir():
                    qa_path = spec_dir / "qa_report.md"
                    if qa_path.exists():
                        return qa_path.read_text(encoding="utf-8")[:3000]

        # 2. Fallback: latest qa_report.md by mtime (pre-convoy compat).
        candidates = sorted(
            spec_root.glob("*/qa_report.md"),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if not candidates:
            return ""
        return candidates[0].read_text(encoding="utf-8")[:3000]

    def _child_log(self, name: str):
        from examples.polecat_swarm.swarm_logger import SwarmLogger

        return SwarmLogger(self.trace.child(name))
