import type { McpUiStyles } from "@modelcontextprotocol/ext-apps/app-bridge";
import type { ThemeMode } from "@/types/preferences/theme";

export const getMcpAppsStyleVariables = (themeMode: ThemeMode): McpUiStyles => {
  const isDark = themeMode === "dark";
  return {
    "--color-background-primary": isDark ? "#171717" : "#ffffff",
    "--color-background-secondary": isDark ? "#262626" : "#f5f5f5",
    "--color-background-tertiary": undefined,
    "--color-background-inverse": undefined,
    "--color-background-ghost": undefined,
    "--color-background-info": undefined,
    "--color-background-danger": undefined,
    "--color-background-success": undefined,
    "--color-background-warning": undefined,
    "--color-background-disabled": undefined,
    "--color-text-primary": isDark ? "#fafafa" : "#171717",
    "--color-text-secondary": isDark ? "#a3a3a3" : "#737373",
    "--color-text-tertiary": undefined,
    "--color-text-inverse": undefined,
    "--color-text-info": undefined,
    "--color-text-danger": undefined,
    "--color-text-success": undefined,
    "--color-text-warning": undefined,
    "--color-text-disabled": undefined,
    "--color-text-ghost": undefined,
    "--color-border-primary": isDark ? "#404040" : "#e5e5e5",
    "--color-border-secondary": undefined,
    "--color-border-tertiary": undefined,
    "--color-border-inverse": undefined,
    "--color-border-ghost": undefined,
    "--color-border-info": undefined,
    "--color-border-danger": undefined,
    "--color-border-success": undefined,
    "--color-border-warning": undefined,
    "--color-border-disabled": undefined,
    "--color-ring-primary": undefined,
    "--color-ring-secondary": undefined,
    "--color-ring-inverse": undefined,
    "--color-ring-info": undefined,
    "--color-ring-danger": undefined,
    "--color-ring-success": undefined,
    "--color-ring-warning": undefined,
    "--font-sans":
      "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    "--font-mono":
      "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
    "--font-weight-normal": undefined,
    "--font-weight-medium": undefined,
    "--font-weight-semibold": undefined,
    "--font-weight-bold": undefined,
    "--font-text-xs-size": undefined,
    "--font-text-sm-size": undefined,
    "--font-text-md-size": undefined,
    "--font-text-lg-size": undefined,
    "--font-heading-xs-size": undefined,
    "--font-heading-sm-size": undefined,
    "--font-heading-md-size": undefined,
    "--font-heading-lg-size": undefined,
    "--font-heading-xl-size": undefined,
    "--font-heading-2xl-size": undefined,
    "--font-heading-3xl-size": undefined,
    "--font-text-xs-line-height": undefined,
    "--font-text-sm-line-height": undefined,
    "--font-text-md-line-height": undefined,
    "--font-text-lg-line-height": undefined,
    "--font-heading-xs-line-height": undefined,
    "--font-heading-sm-line-height": undefined,
    "--font-heading-md-line-height": undefined,
    "--font-heading-lg-line-height": undefined,
    "--font-heading-xl-line-height": undefined,
    "--font-heading-2xl-line-height": undefined,
    "--font-heading-3xl-line-height": undefined,
    "--border-radius-xs": undefined,
    "--border-radius-sm": "4px",
    "--border-radius-md": "8px",
    "--border-radius-lg": "12px",
    "--border-radius-xl": undefined,
    "--border-radius-full": undefined,
    "--border-width-regular": undefined,
    "--shadow-hairline": undefined,
    "--shadow-sm": undefined,
    "--shadow-md": undefined,
    "--shadow-lg": undefined,
  };
};
